### ISSUE TITLE
Where is the permutation happens?

### ISSUE THREAD

**Issue by doem97** [yingyichen-cyy/JigsawViT#1]
For SwinB in22k-ft-in1k experiments, I am think the jigsaw branch is not implemented and not functioning.

Seems the input is just the Imagenet images, without explicitly permutation/shuffling the patches?

I have checked swinb model [here](https://github.com/yingyichen-cyy/JigsawViT/blob/master/imagenet/jigsaw-swin/models/jigsaw_swin.py) and dataloader [here](https://github.com/yingyichen-cyy/JigsawViT/blob/master/imagenet/jigsaw-swin/data/__init__.py)

**Comment by yingyichen-cyy** [comment]
Hi doem97,
Thank you for asking this question. The implementation of the jigsaw branch on Swin transformer is a bit different from that on DeiT backbone. In DeiT, the number of patches remain the same for all layers, but in Swin, the patches will merge from small-sized patches in the initial layer to large-sized patches in the output layer. In this case, it is hard to drop the small-sized patches in the initial layer and predict the exact positions of the remaining small-sized patches only basing on the information provided by the final large-sized patches in the output layer. 

However, since we do want to verify that by adding a branch that predicts the absolute position of patches can help with the overall generalization, our jigsaw branch in Swin is set to predict the absolute positions of the **final merged patches**. Hence, the target of the jigsaw branch is simply set to [torch.arange(self.final_patches)](https://github.com/yingyichen-cyy/JigsawViT/blob/cb2e532a41505d1207704986711a46ec02af0a6f/imagenet/jigsaw-swin/models/jigsaw_swin.py#L578) in this case. Details can be referred to the supplementary material [Ablation study on ImageNet](https://arxiv.org/pdf/2207.11971.pdf). Hope these can address your concerns.

P.s. maybe there could be some misunderstanding towards the methodology in our paper. We use "patch masking" instead of permuting the image patches. You can refer to [Issue 3](https://github.com/yingyichen-cyy/JigsawViT/issues/3) for more details.
