### ISSUE TITLE
Jagsaw Puzzle + ViT SSL pre-training

### ISSUE THREAD

**Issue by sagizty** [yingyichen-cyy/JigsawViT#4]
Dear authors,

Congratulations on your interesting work, cheers!
I wonder your work would further benefit the community by altering a bit to do SSL pre-training. 

As the original Jagsaw Puzzle paper in 2016 did it but no recent follow-ups, enabling a recent comparison with your code looks not painstaking but beneficial?

In my understanding, we can achieve this point by removing the classification loss in your code? May I know if it’s correct?

Thanks, a lot.

**Comment by yingyichen-cyy** [comment]
Dear sagizty, 

Thank you for your interest in our work:)

We indeed tried to conduct our jigsaw branch alone for pre-training, but it was very hard for us to compare with the SoTAs at that time due to a lack of computational resources. However, we do feel that jigsaw-branch can be served as a SSL pre-training loss, and the performance may be further improved together with a contrastive loss.

**Comment by sagizty** [comment]
Thanks! I think we are in same shoes though. Have a nice day.
